#!/bin/bash

## Compile files ##

vlib work

vcom -work work CONSTANTS.vhd
vcom -work work DATA_BUFFER.vhd
vcom -work work IP_MANAGER.vhd
vcom -work work TOP_ENTITY.vhd

# if [ "$(ps | grep vsim)" = "" ]
# then
#	vsim -gui -do "source simul.tcl" &
# fi
